# Generated by Django 5.0.1 on 2024-07-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0017_checkout_dateslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='timeslot',
        ),
    ]
